language: python
python: 2.7
env:
    - LOGSTASH_VERSION=6.5.4
addons:
  apt:
    packages: default-jre-headless
install:
    - cd $HOME
    - easy_install vsc-base
    - wget https://artifacts.elastic.co/downloads/logstash/logstash-${logstash_version}.tar.gz
    - tar -xzf logstash-${LOGSTASH_VERSION}.tar.gz
    - export PATH=$HOME/logstash-${LOGSTASH_VERSION}/bin:$PATH
script:
    - cd $TRAVIS_BUILD_DIR/tests && python runtest.py
